---
- name: Compile C++ Client Program
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install g++
      become: true
      package:
        name: g++
        state: present

    - name: Compile client.cpp
      shell: g++ -o client client.cpp

    - name: Confirm compilation success
      stat:
        path: ~/test_bench/client
      register: client_compiled

    - name: Print compilation status
      debug:
        msg: "Client compilation {{ 'succeeded' if client_compiled.stat.exists else 'failed' }}."

